# Generated by Django 5.2.4 on 2025-08-05 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificationpreference_hr_manager_and_more'),
        ('users', '0003_hrmanager_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='HRManager who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.hrmanager'),
        ),
    ]
