# Generated by Django 5.2.4 on 2025-07-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmatchingcriteria',
            name='rule',
            field=models.CharField(choices=[('same', 'Same'), ('not_same', 'Not Same')], max_length=20),
        ),
    ]
