# Generated by Django 5.2.4 on 2025-07-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='hr_manager_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='hr_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hrmanager'),
        ),
    ]
