# Generated by Django 5.2.4 on 2025-07-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_campaign_hr_manager_id_campaign_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='hr_manager',
            new_name='hr_manager_id',
        ),
    ]
