# Generated by Django 5.2.4 on 2025-07-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_hr_manager_campaign_hr_manager_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='hr_manager_id',
            new_name='hr_manager',
        ),
    ]
