# Generated by Django 5.2.4 on 2025-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignworkflowstate',
            name='current_step',
            field=models.IntegerField(choices=[(1, 'Créer Campagne'), (2, 'Télécharger Employés'), (3, 'Définir Critères'), (4, 'Générer Paires'), (5, 'Confirmer et Envoyer')], default=1),
        ),
    ]
