# Generated by Django 5.2.4 on 2025-07-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_campaign_employee_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_email_8f5bbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_campaig_9b4e17_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_import__4ebb63_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='import_batch_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='imported_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
    ]
