# Generated by Django 5.2.4 on 2025-07-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaignworkflowlog_campaignworkflowstate'),
        ('employees', '0003_remove_employee_employees_e_email_8f5bbc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('email', 'campaign')},
        ),
    ]
