# Generated by Django 5.2.4 on 2025-08-01 19:13

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmanager',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (JPG, PNG, WebP supported)', null=True, upload_to=users.models.profile_picture_upload_path),
        ),
    ]
